<?php
return array (
  'key' => '5D9A2A9FA39038F9',
  'iv' => '1E24CF708A14CE81',
  'mode' => '0',
  'yuan' => '.m3u8,.flv',
  'api' => 'youku,qq,iqiyi$https://111.com/json.php?url=||0||0||0||auto||0#qq,EC$http://127.0.0.1/index.php?url=||0||0||0||auto||User-Name: 超级播放器,User-Id: 6',
  'password' => 'pHiEFwLCz5hTkn6r',
  'redis_type' => '1',
  'redis_host' => '127.0.0.1',
  'redis_port' => '6379',
  'redis_pass' => '',
  'limit_time' => '60',
  'limit_max' => '30',
  'limit_handle' => '3600',
  'IP' => '0',
  '__token__' => '6d87365edf0c2331dd88113dd44dfc86',
  'other' => 
  array (
    'danMu_pro' => '0',
    'danMu_cache' => '3600',
    'danMu_audit' => '0',
    'danMu_vab' => '草,操,妈,逼,滚,网址,网站,关注,wx,微信,qq,QQ,百度,搜索,公众号,看片,习近平,法轮,迫害,翻墙',
  ),
  'jx' => 
  array (
    'youku' => 
    array (
      0 => 'https://111.com/json.php?url=||0||0||0||auto||0',
    ),
    'qq' => 
    array (
      0 => 'https://111.com/json.php?url=||0||0||0||auto||0',
      1 => 'http://127.0.0.1/index.php?url=||0||0||0||auto||User-Name: 超级播放器,User-Id: 6',
    ),
    'iqiyi' => 
    array (
      0 => 'https://111.com/json.php?url=||0||0||0||auto||0',
    ),
    'EC' => 
    array (
      0 => 'http://127.0.0.1/index.php?url=||0||0||0||auto||User-Name: 超级播放器,User-Id: 6',
    ),
  ),
  'tips' => 
  array (
    'bj' => '/player/img/bj.webp',
    'style' => '1',
    'empty_title' => '亲爱的⚡用户',
    'empty_txt' => '播放器未获取到任何播放地址',
    'jx_title' => '非常抱歉',
    'jx_txt' => '资源解析失败请稍后刷新重试，如依旧无法解决请联系网站管理员。',
    'qh_title' => '糟糕~解析失败',
    'qh_txt' => '请从下面选择其他接口尝试',
    'ip_title' => '非常糟糕',
    'ip_txt' => '因您访问过于频繁已进入临时冻结，如有疑问请联系网站管理员',
    'vague' => '1',
  ),
  'lg' => 
  array (
    'ad-name' => '广告',
    'ad-close' => '关闭',
    'ad-time' => '倒计时',
    'ad-link' => '查看详情',
    'ad-tos' => '打开声音',
    'ad-tso' => '关闭声音',
    'ad-s' => '秒',
    'dm-velocity' => '弹幕速度',
    'dm-size' => '字体大小',
    'dm-opacity' => '不透明度',
    'dm-br' => '弹幕范围',
    'dm-direction' => '弹幕方向',
    'dm-roll' => '滚动',
    'dm-top' => '顶部',
    'dm-bottom' => '底部',
    'dm-color' => '弹幕颜色',
    'dm-send' => '发送',
    'dm-input' => '来发个弹幕吧~',
    'dm-please' => '要输入弹幕内容啊喂',
    'dm-loading-err' => '弹幕加载失败：',
    'dm-Sign' => '请先登录~',
    'dm-rule' => '请大家遵守弹幕礼仪，文明发送弹幕！',
    'dm-npo' => '条弹幕列队来袭~做好准备吧！',
    'dm-welcome' => '一条弹幕都没有，赶紧来一发吧！',
    'dm-text' => '弹幕内容长度最大30位!!!',
    'dm-label' => '发弹幕',
    'dm-dj' => 's后解除冻结',
    'zm-error' => '字幕加载失败!!!',
    'zm-tcl' => '弹幕中必须包含中文',
    'zm-off' => '字幕开关',
    'gtc' => '默认',
    'moderate' => '适中',
    'minuteness' => '极小',
    'less' => '较小',
    'maximum' => '极大',
    'more' => '较大',
    'one' => '半屏',
    'es' => '极慢',
    'slower' => '较慢',
    'faster' => '极快',
    'express' => '较快',
    'list' => '选集',
    'list-label' => '选集列表',
    'single-row' => '单列',
    'many' => '多列',
    'ps' => '倒叙',
    'remarks' => '海量影片免费看',
    'year' => '年度',
    'hits' => '热播片场',
    'error2' => '错误次数过多请休息休息',
    'error-tips' => '选集接口请求失败',
    'retry' => '重新尝试',
    'unusual' => '接口异常无法切换下一集',
    'skip' => 's后自动播放下一集',
    'rm1' => '上次看到',
    'rm2' => '继续上次播放',
    'try' => '试看结束',
    'rm4' => 's后为您播放，是否立即跳转？',
    'rm5' => '视频已准备就绪，即将为您播放',
    'rm6' => '完成',
    'rm7' => '失败',
    'rm8' => '播放器连接...',
    'rm9' => '等待视频连接中',
    'yes' => '是',
    'no' => '否',
    'nav' => '更多功能',
  ),
);