<?php
return array (
  'time' => '1',
  'qfe' => '1',
  'rm' => '2',
  'pip' => '1',
  'revolve' => '1',
  'lock' => '1',
  'next_bnt' => '1',
  'next_auto' => '1',
  'next_time' => '10',
  'danMu_on' => '1',
  'danMu_api' => '1$/index.php/index/dm?ac=dm#2$https://dmku.byteamone.cn/dmku/?ac=dm',
  'danMu_input' => '1',
  'danMu_user' => '0',
  'danMu_interval' => '10',
  'danMu_length' => '22',
  'color' => '#24a5ff',
  'wait_time' => '10',
  'wait_color' => 'hsla(0,0%,100%,.7)',
  'user' => '',
  'random_img' => '/player/img/bj/0.jpg#/player/img/bj/1.jpg#/player/img/bj/2.jpg#/player/img/bj/3.jpg#/player/img/bj/4.jpg#/player/img/bj/5.jpg#/player/img/bj/6.jpg#/player/img/bj/7.jpg',
  'random' => '1',
  'tga' => '',
  'try-time' => '3',
  'try-user' => '',
  'force' => '1',
  'handle' => '0',
  'player' => 'art',
  'yuan' => '',
  'seat' => '1',
  'zm_off' => '0',
  'zm_style' => 'color: #fff; font-size: 1.6vw;background:#000c;',
    'autoOrientation' => '1',
    'number'=>'1',
  'ads' => 
  array (
    'user' => '',
    'state' => '1',
    'pic' => 
    array (
      'time' => '6',
      'img' => 'https://m.ykimg.com/material/0A03/A1/202204/0426/3063067/1650981163721/0D0100006267FD861861622399395632.jpg',
      'link' => 'https://www.vmall.com/portal/activity/index.html?pn=MatePC',
    ),
    'vod' => 
    array (
      'time' => 'https://consumer.huawei.com/content/dam/huawei-cbg-site/cn/mkt/pdp/phones/mate50-pro/video/tvc-video.mp4',
      'link' => 'https://www.vmall.com/portal/activity/index.html?pn=MatePC',
    ),
    'pause' => 
    array (
      'state' => '1',
      'img' => 'https://m.ykimg.com/material/0A03/A1/202204/0426/3063067/1650981163721/0D0100006267FD861861622399395632.jpg',
      'link' => '#',
    ),
  ),
  'gx' => 
  array (
    'pic' => 'https://img10.360buyimg.com/ddimg/jfs/t1/176340/18/8164/733759/609395e4E2df09db0/80b3d377da26e626.jpg',
    'color' => '#E50916',
    'logo' => '/player/img/logo.png',
    'logo_position' => '2',
    'pc_logo_width' => '15%',
    'wap_logo_width' => '100px',
    'marquee_s' => '1',
    'marquee_time' => '60',
    'marquee' => '欢迎访问祝你观影愉快',
    'marquee_style' => '#E50916',
    'marquee_speed' => '10',
  ),
  'row' => 
  array (
    'player' => 'plyr',
  ),
  'dp' => 
  array (
    'live' => '0',
    'autoplay' => '1',
    'lang' => 'zh-cn',
    'screenshot' => '1',
    'hotkey' => '1',
    'airplay' => '1',
    'chromecast' => '1',
    'preload' => 'auto',
    'volume' => '0.8',
    'playbackSpeed' => '0.5, 0.75, 1, 1.25, 1.5, 2',
    'contextmenu' => '超级播放器$https://www.maccmsbox.com/details371.html#作者$https://wpa.qq.com/msgrd?@v=3&uin=602524950&site=qq&menu=yes',
  ),
  'art' => 
  array (
    'isLive' => '0',
    'autoplay' => '1',
    'muted' => '0',
    'volume' => '0.8',
    'autoSize' => '0',
    'playbackRate' => '1',
    'aspectRatio' => '1',
    'screenshot' => '1',
    'hotkey' => '1',
    'pip' => '1',
    'fullscreen' => '1',
    'miniProgressBar' => '1',
    'lang' => 'zh-cn',
    'lock' => '1',
    'fastForward' => '1',
    'airplay' => '1',
    'contextmenu' => '超级播放器$https://www.maccmsbox.com/details371.html#作者$https://wpa.qq.com/msgrd?@v=3&uin=602524950&site=qq&menu=yes',
  ),
  'ck' => 
  array (
    'live' => '0',
    'autoplay' => '1',
    'barHideTime' => '3000',
    'volume' => '0.8',
    'playbackrateOpen' => '1',
    'documentFocusPause' => '1',
    'mouseWheelVolume' => '1',
    'keyVolume' => '1',
    'playbackrateList' => '0.75,1,1.25,1.5,2,4',
    'contextmenu' => '超级播放器$https://www.maccmsbox.com/details371.html#作者$https://wpa.qq.com/msgrd?@v=3&uin=602524950&site=qq&menu=yes',
  ),
  'xg' => 
  array (
    'volume' => '0.6',
    'videoInit' => '1',
    'playbackRate' => '0.75,1,1.25,1.5,2,4',
    'pip' => '1',
    'screenShot' => '1',
    'keyShortcut' => '1',
    'airplay' => '1',
    'lang' => 'zh-cn',
  ),
  'mp' => 
  array (
    'autoplay' => '1',
    'loop' => '0',
    'muted' => '0',
    'lang' => 'zh-cn',
    'volume' => '0.8',
    'live' => '0',
    'autoOrientaion' => '1',
    'dragSpotShape' => '0',
    'closeControlsTimer' => '3500',
    'showMiniProgress' => '1',
    'contextmenu' => '超级播放器$https://www.maccmsbox.com/details371.html',
  ),
  'plyr' => 
  array (
    'settings' => '1',
    'pip' => '1',
    'airplay' => '1',
    'fullscreen' => '1',
    'keyboard' => '1',
    'autoplay' => '1',
    'volume' => '0.8',
    'muted' => '0',
    'i18n' => '{"speed": "播放速度","normal": "正常"}',
  ),
);